pcc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views



urlpatterns = [
    path('pet/', include('pet.urls')),
    path('admin/', admin.site.urls),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('adote/', include('adote.urls')),
    path('comentarios/', include('comentarios.urls')),
    path('donations/', include('donations.urls')),
    path('usuario/', include('usuario.urls')),
    path('denuncia/', include('denuncia.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0]) 

pet/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.readall, name='index'),
    path('create/', views.create, name='Criar'),
    path('read/<int:id_animal>/', views.read, name='Ler'),
    path('update/<int:id_animal>/', views.update, name='Atualizar'),
    path('delete/<int:id_animal>/', views.delete, name='Deletar'),
    path('delete/confirm/<int:id_animal>/', views.confirmdelete, name='pet_confirm_delete'),
    path('user_index/', views.user_index, name='user_index'),
    path('user_detail/<int:animal_id>/', views.user_detail, name='user_detail'),
    path('admin-dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('apadrinhar/<int:animal_id>/', views.apadrinhar_view, name='apadrinhar_animal'),
    path('apadrinhamento/<int:animal_id>/', views.apadrinhamento_detalhes, name='apadrinhamento_detalhes'),
    path('about/', views.about, name='about'),
    path('vet/', views.veterinarian, name='veterinarian'),
    path('services/', views.services, name='services'),
    path('gallery/', views.gallery, name='gallery'),
    path('blog/', views.blog, name='blog'),
    path('comentarios/', views.pricing, name='pricing'),
    path('contact/', views.contact, name='contact'),
    path('admin/', views.admin, name='admin'),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
]

pet/models.py
from django.db import models
from django.utils import timezone
from django.core.exceptions import ValidationError

class Animal(models.Model):
    nome = models.CharField(max_length=50, default='')
    raca = models.CharField(max_length=50, default='Desconhecida', null=True, blank=True)
    data_nascimento = models.DateField(default=str(timezone.now().date()))
    imagem = models.ImageField(upload_to='animais/', blank=True, null=True)
    SEXO_CHOICES = [
        ('M', 'Masculino'),
        ('F', 'Feminino'),
    ]
    
    
    sexo = models.CharField(max_length=1, choices=SEXO_CHOICES, default='M')

    descricao = models.TextField(default='Sem descrição')

    def clean(self):
        
        if self.data_nascimento > timezone.now().date():
            raise ValidationError("A data de nascimento não pode ser no futuro.")

    def __str__(self):
        return self.nome

pet/forms.py
from django.forms import ModelForm
from pet.models import Animal


class AnimalForm(ModelForm):

    class Meta: 
        model = Animal 
        fields = '__all__'

pet/views.py
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from .forms import AnimalForm
from .models import Animal
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth import login
from django.urls import reverse
from adote.forms import AdotarAnimalForm
from donations.models import Doacao
from comentarios.models import Comentario
from adote.models import Adocao
from denuncia.models import Denuncia



@login_required
def create(request):
    if request.method == 'POST':
        form = AnimalForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('admin'))
    else:
        form = AnimalForm()
    return render(request, 'formCreate.html', {'form': form})


@login_required
def readall(request):
    animais = Animal.objects.all()
    first_animal = animais.first() if animais.exists() else None
    return render(request, "index.html", {'animais': animais, 'animal': first_animal})


@login_required
def read(request, animal_id):
    animal = get_object_or_404(Animal, pk=animal_id)
    return render(request, 'user_detail.html', {'animal': animal})


@login_required
def update(request, id_animal):
    animal = get_object_or_404(Animal, pk=id_animal)
    if request.method == 'POST':
        form = AnimalForm(request.POST, request.FILES, instance=animal)
        if form.is_valid():
            form.save()
            return redirect('admin')  
    else:
        form = AnimalForm(instance=animal)
    return render(request, 'formupdate.html', {'form': form, 'animal': animal})


@login_required
def delete(request, id_animal):
    animal = get_object_or_404(Animal, pk=id_animal)
    if request.method == 'POST':
        animal.delete()
        return HttpResponseRedirect(reverse('admin'))
    
    return render(request, 'confirmdelete.html', {'animal': animal})


@login_required
def confirmdelete(request, id_animal):
    animal = get_object_or_404(Animal, pk=id_animal)
    return render(request, 'confirmdelete.html', {'animal': animal})


@login_required
@user_passes_test(lambda u: u.is_staff)
def admin_dashboard(request):
    animais = Animal.objects.all()
    return render(request, 'index.html', {'animais': animais})


def user_index(request):
    animais = Animal.objects.all()
    return render(request, 'index.html', {'animais': animais})


def user_detail(request, animal_id):
    animal = get_object_or_404(Animal, pk=animal_id)
    if request.method == 'POST':
        form = AdotarAnimalForm(request.POST)
        if form.is_valid():
            adotado = form.save(commit=False)
            adotado.animal = animal
            adotado.save()
            return redirect('listar_adocoes')
    else:
        form = AdotarAnimalForm()
    return render(request, 'user_detail.html', {'animal': animal, 'form': form})





@login_required
def about(request):
    return render(request, 'about.html')


@login_required
def veterinarian(request):
    animais = Animal.objects.all()
    return render(request, 'vet.html', {'animais': animais})


@login_required
def services(request):
    return render(request, 'services.html')


@login_required
def gallery(request):
    animais = Animal.objects.all()
    return render(request, 'gallery.html', {'animais': animais})


@login_required
def admin(request):
    animais = Animal.objects.all()
    adocoes = Adocao.objects.all()
    return render(request, 'blog.html', {'animais': animais, 'adocoes': adocoes})


@login_required
def pricing(request):
    comentarios = Comentario.objects.all()
    denuncias = Denuncia.objects.filter(denunciante=request.user)
    return render(request, 'pricing.html', {'comentarios': comentarios, 'denuncias': denuncias})


@login_required
def blog(request):
    return render(request, 'blog.html')


@login_required
def contact(request):
    doacao = Doacao.objects.filter(doador=request.user)
    return render(request, 'contact.html', {'doacao': doacao})












@login_required
def apadrinhamento_detalhes(request, animal_id):
    user = request.user
    animal = get_object_or_404(Animal, id=animal_id)
    context = {
        'user': user,
        'animal': animal
    }
    return render(request, 'pet/apadrinhar.html', context)

def apadrinhar_view(request, animal_id):
    if request.method == 'POST':
        animal = get_object_or_404(Animal, id=animal_id)
        
        return JsonResponse({'message': 'O animal foi apadrinhado, entraremos em contato'})
    return JsonResponse({'error': 'Requisição inválida'}, status=400)

templates/pet/adoption_info.html
{% extends '_base.html' %}
{% load static %}

{% block content %}
    <div class="adoption-header">
        <img src="{% static 'img/ONGs.jpg' %}" alt="ONGs Image">
        <div class="adoption-header-overlay">
            <h1>Somos Cachorros</h1>
        </div>
    </div>
    
    <div class="adoption-main">
        <div class="adoption-info">
            <div class="info-text">
                <h2>Agradecemos seu interesse em adotar um cão da Patas Solidárias.</h2>
                <p>Do ponto de vista do animal, ser abandonado é doloroso...</p>
                <p>Em caso de não adaptação, o animal deve ser devolvido para a Patas Solidárias.</p>
            </div>
        </div>
        
        <div class="location-info">
            <div class="location-text">
                <p>Nosso abrigo fica em Leopoldo de Bulhões, Goiás...</p>
                <p>Estamos doando animais para Anápolis e cidades até 45 km do Centro.</p>
                <p>Para outras localidades, consulte uma ONG ou o CCZ de sua cidade.</p>
                <p>Dúvidas sobre o processo de adoção? Confira na página do animal ou entre em contato conosco.</p>
            </div>
        </div>
    </div>
    
    <div class="adoption-footer">
        <img src="{% static 'img/iss.png' %}" alt="ISS Image">
        <div class="footer-content">
            <h2>Obrigado pela atenção</h2>
        </div>
    </div>
{% endblock %}

templates/pet/user_index.html
{% extends '_base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'admin/css/style_projeto.css' %}">
{% endblock %}

{% block content %}
    <h1>Animais cadastrados</h1>
    <div class="image-row">
        {% for animal in animais %}
            <a href="{% url 'user_detail' animal.id %}" class="animal-card">
                <div class="animal-image">
                    <img src="{% if animal.imagem %}{{ animal.imagem.url }}{% else %}{% static 'img/placeholder.png' %}{% endif %}" alt="Imagem do Animal">
                </div>
                <div class="animal-info">
                    <h3>{{ animal.nome }}</h3>
                    <p><strong>Raça:</strong> {{ animal.raca }}</p>
                    <p><strong>Data de Nascimento:</strong> {{ animal.data_nascimento }}</p>
                    <p><strong>Sexo:</strong> {{ animal.get_sexo_display }}</p>
                </div>
            </a>
        {% endfor %}
    </div>
{% endblock %}